### ISSUE TITLE
Improve ValueError handling, maybe switch to Startstop Exception

### ISSUE THREAD

**Issue by yuriescl** [yuriescl/startstop#2]
$ startstop run --name uvicorn
```
Traceback (most recent call last):
  File "/home/yuri/.cache/pypoetry/virtualenvs/polbox-requests-lTwMA7Ai-py3.10/bin/startstop", line 8, in <module>
    sys.exit(main())
  File "/home/yuri/.cache/pypoetry/virtualenvs/polbox-requests-lTwMA7Ai-py3.10/lib/python3.10/site-packages/startstop.py", line 1029, in main
    raise ValueError("command is None")
ValueError: command is None
```

**Comment by yuriescl** [comment]
Done
